"""Enrich existing data models

Revision ID: 4
Revises: 3
Create Date: 2024-07-25 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4'
down_revision: Union[str, None] = '3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('start_location_country_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('start_location_province_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('start_location_city_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('address', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('lng', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'cities', ['start_location_city_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'provinces', ['start_location_province_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'countries', ['start_location_country_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'task_categories', ['category_id'], ['id'])
    op.add_column('task_steps', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('task_steps', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('task_steps', sa.Column('estimated_time', sa.Integer(), nullable=True))
    op.add_column('task_steps', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_steps', 'start_time')
    op.drop_column('task_steps', 'estimated_time')
    op.drop_column('task_steps', 'lng')
    op.drop_column('task_steps', 'lat')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'lng')
    op.drop_column('tasks', 'lat')
    op.drop_column('tasks', 'address')
    op.drop_column('tasks', 'start_location_city_id')
    op.drop_column('tasks', 'start_location_province_id')
    op.drop_column('tasks', 'start_location_country_id')
    op.drop_column('tasks', 'category_id')
    # ### end Alembic commands ###
