"""Add task kinds and link them to tasks

Revision ID: 6
Revises: 5
Create Date: 2024-08-30 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6'
down_revision: Union[str, None] = '5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_kinds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_kinds_id'), 'task_kinds', ['id'], unique=False)
    op.create_index(op.f('ix_task_kinds_name'), 'task_kinds', ['name'], unique=True)
    op.add_column('tasks', sa.Column('task_kind_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'task_kinds', ['task_kind_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'task_kind_id')
    op.drop_index(op.f('ix_task_kinds_name'), table_name='task_kinds')
    op.drop_index(op.f('ix_task_kinds_id'), table_name='task_kinds')
    op.drop_table('task_kinds')
    # ### end Alembic commands ###
